service: ddarchitect-glue-crawling-dfi
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'preprod'}
  region: eu-west-1
  iam:
    role: ${self:custom.${self:provider.stage}.aws_lambda_role}
  deploymentBucket:
    name: ${self:custom.${self:provider.stage}.deployment_bucket}

package:
  exclude:
    - '**'
  include:
    - 'lambda_package/**'

functions:
  api:
    name: ddarchitect-glue-crawling-dfi-${self:provider.stage}
    handler: lambda_package.handler.main
    memorySize : 512
    timeout: 180
    layers:
      - arn:aws:lambda:eu-west-1:336392948345:layer:AWSSDKPandas-Python39:2
    tags:
      PROJECT: ${self:custom.${self:provider.stage}.aws_project_tag}
    vpc:
      securityGroupIds: ${self:custom.${self:provider.stage}.securityGroupIds}
      subnetIds: ${self:custom.${self:provider.stage}.subnetIds}
    events:
      - alb:
          listenerArn: ${self:custom.${self:provider.stage}.listenerArn}
          priority: 5
          multiValueHeaders: true
          conditions:
            path: /dfi-crawler

plugins:
  - serverless-python-requirements
  - serverless-stage-manager

custom:
  stages:
    - preprod
    - prod
  pythonRequirements:
    pythonBin: python3
  preprod: ${file(serverless_config/preprod.yml)}
  prod: ${file(serverless_config/prod.yml)}
