name: Deploy on prod
on:
  release:
    types: ['published', 'edited']
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Deploy serverless lambda
    runs-on: decathlon
    env:
      SLS_VERSION: 3.1.1

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::585305677161:role/BIGDATA-GITHUBACTIONS-DDARCHITEC-INFRA
        aws-region: eu-west-1

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Serverless Framework
      run: npm install -g serverless@${{ env.SLS_VERSION }}

    - run: npm ci

    - name: Deploy Lambda functions
      run: sls deploy --stage prod

